blog/urls.py
from django.urls import path

from . import views

from .views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostUpdateView, BlogPostDeleteView

app_name = 'blog'

urlpatterns = [
    path('blog/', BlogPostListView.as_view(), name='blog'),
    path('blogpost_detail/<int:pk>/', BlogPostDetailView.as_view(), name='blogpost_detail'),
    path('blog/new/', BlogPostCreateView.as_view(), name='blogpost_create'),
    path('blog/update/<int:pk>/', BlogPostUpdateView.as_view(), name='blogpost_update'),
    path('books/delete/<int:pk>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),

    # path('contacts/', ContactsView.as_view(), name='contacts'),


    # path('home/', views.home, name='home'),
    # path('contacts/', views.contacts, name='contacts'),
    # path('product_detail/<int:product_id>/', views.product_detail, name='product_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),

]

blog/models.py
from django.db import models


class BlogPost(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано или нет')
    views_count = models.IntegerField(default=0)



    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'запись в блоге'
        verbose_name_plural = 'записи в блоге'
        ordering = ['title']

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from .models import BlogPost

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

class BlogPostListView(ListView):
    model = BlogPost
    template_name = 'blog/blogpost_list.html'
    context_object_name = 'blog'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_published=True)


class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = 'blog/blogpost_detail.html'
    context_object_name = 'blogpost'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views_count += 1
        obj.save()
        return obj


class BlogPostCreateView(CreateView):
    model = BlogPost
    fields = ['title', 'content']
    template_name = 'blog/blogpost_form.html'
    success_url = reverse_lazy('blog:blog')


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    fields = ['title', 'content']
    template_name = 'blog/blogpost_form.html'

    def get_success_url(self):
        return reverse_lazy('blog:blogpost_detail', kwargs={'pk': self.object.pk})


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    template_name = 'blog/blogpost_confirm_delete.html'
    success_url = reverse_lazy('blog:blog')

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Блог{% endblock %}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>

{% include 'blog/menu.html' %}

<div class="container">

    {% block content %}{% endblock %}


    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script type="text/javascript" src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'blog/base.html' %}

{% block title %}{{blogpost.title}}{% endblock %}

{% block content %}


<h1>Удаление статьи</h1>

<h2>Удаление статьи</h2>
<p>Вы действительно хотите удалить {{ blogpost.title }}?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'blog:blog' %}" class="btn btn-primary">Отменить</a>
</form>

{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'blog/base.html' %}

{% block title %}{{blogpost.title}}{% endblock %}

{% block content %}


<h1>{{blogpost.title}}</h1>
<p>Контент: {{ blogpost.content }}</p>
<p>Дата публикации: {{ blogpost.created_at|date:"d M Y" }}</p>
<p>Опубликовано ли: {{ blogpost.is_published }}</p>
<p>Количество просмотров: {{ blogpost.views_count }}</p>

<a href="{% url 'blog:blogpost_update' blogpost.pk %}" class="btn btn-secondary">Редактировать</a>
<a href="{% url 'blog:blogpost_delete' blogpost.pk %}" class="btn btn-danger">Удалить</a>
<a href="{% url 'blog:blog' %}" class="btn btn-primary">Вернуться к списку</a>

{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'blog/base.html' %}

{% block title %}Создать статью{% endblock %}

{% block content %}


<h2>Создать статью</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'blog:blog' %}" class="btn btn-primary">Отменить</a>
</form>


{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'blog/base.html' %}

{% block title %}Список статей{% endblock %}

{% block content %}

{% include 'blog/header.html' %}

<div class="row text-center">
    <ul class="list-group">
    {% for blogpost in blog %}
    <li class="list-group-item">
        <a href="{% url 'blog:blogpost_detail' blogpost.pk %}">{{ blogpost.title }}</a>
    </li>
    {% endfor %}
    </ul>
</div>

{% endblock %}

blog/templates/blog/header.html
<header>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блог</h1>
    <nav>
    <a href="{% url 'blog:blog' %}">Список статей</a>
    <a href="{% url 'blog:blogpost_create' %}">Добавить статью</a>
    </nav>
    <p class="lead">Самый интересный блог на Земле!</p>
    </div>
</header>

blog/templates/blog/menu.html
<nav>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/home/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
    </div>
</nav>