blog/urls.py
from django.urls import path

from . import views

from .views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostUpdateView, BlogPostDeleteView

app_name = 'blog'

urlpatterns = [
    path('blog/', BlogPostListView.as_view(), name='blog'),
    path('blogpost_detail/<int:pk>/', BlogPostDetailView.as_view(), name='blogpost_detail'),
    path('blog/new/', BlogPostCreateView.as_view(), name='blogpost_create'),
    path('blog/update/<int:pk>/', BlogPostUpdateView.as_view(), name='blogpost_update'),
    path('books/delete/<int:pk>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),

    # path('contacts/', ContactsView.as_view(), name='contacts'),


    # path('home/', views.home, name='home'),
    # path('contacts/', views.contacts, name='contacts'),
    # path('product_detail/<int:product_id>/', views.product_detail, name='product_detail'),
]

catalog/urls.py
from django.urls import path

from . import views

from .views import ProductListView, ProductDetailView, ContactsView, ProductCreateView, ProductUpdateView, ProductDeleteView, IsPublishedProductView, ProductByCategoryView

app_name = 'catalog'

urlpatterns = [
    path('home/', ProductListView.as_view(), name='home'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('new/', ProductCreateView.as_view(), name='product_create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),

    path('is_publishes/<int:pk>/', IsPublishedProductView.as_view(), name='product_is_published'),
    path('category/<int:category_id>/', ProductByCategoryView.as_view(), name='products_by_category'),



    # path('home/', views.home, name='home'),
    # path('contacts/', views.contacts, name='contacts'),
    # path('product_detail/<int:product_id>/', views.product_detail, name='product_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),

]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views
from .views import RegisterView


app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='catalog:home'), name='logout'),

]

catalog/models.py
from django.db import models

from users.models import CustomUser


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.CharField(max_length=150, verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ['name']

class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.CharField(max_length=150, verbose_name='Описание')
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', verbose_name='Категория')
    price = models.IntegerField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    is_published = models.BooleanField(default=False)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='products_of_user', verbose_name='Владелец', blank=True, null=True)

    def __str__(self):
        return f'{self.name} за {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['name']
        permissions = [
            ('can_unpublish_product', 'Can unpublish product'),
        ]

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'category', 'price']
        exclude = ['owner']


    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите название',
        })

        self.fields['description'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите описание',
        })

        self.fields['category'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Выберете категорию',
        })

        self.fields['price'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите цену',
        })


    def clean_name(self):

        forbidden_words = {
            'казино', 'криптовалюта', 'крипта', 'биржа',
            'дешево', 'бесплатно', 'обман', 'полиция', 'радар'
        }
        name = self.cleaned_data.get('name')

        for word in forbidden_words:
            if word in name.lower():
                raise ValidationError('Запрещенное слово в названии товара!')
        return name

    def clean_description(self):

        forbidden_words = {
            'казино', 'криптовалюта', 'крипта', 'биржа',
            'дешево', 'бесплатно', 'обман', 'полиция', 'радар'
        }
        description = self.cleaned_data.get('description')

        for word in forbidden_words:
            if word in description.lower():
                raise ValidationError('Запрещенное слово в описании товара!')
        return description


    def clean_price(self):

        price = self.cleaned_data.get('price')

        if price < 0:
            raise ValidationError('Цена не может быть отрицательной!')
        return price

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseForbidden
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from django.core.cache import cache

from catalog.models import Product
from .forms import ProductForm
from .services import ProductListInCategory
from django.shortcuts import render, get_object_or_404

from django.views.generic import ListView, DetailView, TemplateView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView


class ProductByCategoryView(ListView):
    model = Product
    template_name = 'catalog/products_by_category.html'
    context_object_name = 'products'

    def get_queryset(self):
        category_id = self.kwargs['category_id']
        return ProductListInCategory.product_list(category_id)



class IsPublishedProductView(LoginRequiredMixin, View):
    def post(self, request, pk):
        product = get_object_or_404(Product, id=pk)

        if not request.user.has_perm('catalog.can_unpublish_product'):
            return HttpResponseForbidden('У вас нет права для изменения статуса продукта')

        product.is_published = True
        product.save()

        return redirect('catalog:product_detail', pk=pk)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy('catalog:home')
    permission_required = 'catalog.change_product'

    def has_permission(self):
        obj = self.get_object()
        return super().has_permission() or obj.owner == self.request.user


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = 'catalog/product_confirm_delete.html'
    success_url = reverse_lazy('catalog:home')
    permission_required = 'catalog.delete_product'

    def has_permission(self):
        obj = self.get_object()
        return super().has_permission() or (
                obj.owner == self.request.user or self.request.user.groups.filter(name='Модератор продуктов').exists()
        )

    def handle_no_permission(self):
        return HttpResponseForbidden('У вас нет права на удаление продукта')


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/home.html'
    context_object_name = 'products'

    def get_queryset(self):
        queryset = cache.get('products_queryset')
        if not queryset:
            queryset = super().get_queryset()
            cache.set('products_queryset', queryset, 60 * 15)
        return queryset


# def home(request):
#     products = Product.objects.all()
#     context = {
#         'products': products
#     }
#     return render(request, 'catalog/home.html', context=context)


class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        return HttpResponse(f'{name}, спасибо за сообщение')

# def contacts(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         phone = request.POST.get('phone')
#         message = request.POST.get('message')
#         return HttpResponse(f'{name}, спасибо за сообщение')
#     return render(request, 'catalog/contacts.html')

@method_decorator(cache_page(60*15), name='dispatch')
class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'
    context_object_name = 'product'


# def product_detail(request, product_id):
#     product = get_object_or_404(Product, id=product_id)
#     context = {
#         'product': product,
#     }
#     return render(request, 'catalog/product_detail.html', context=context)

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Скайпро{% endblock %}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>

{% include 'catalog/menu.html' %}

<div class="container">

    {% block content %}{% endblock %}


    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script type="text/javascript" src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block title %}Skystore{% endblock %}

{% block content %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="row text-center">
     <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

catalog/templates/catalog/header.html
<header>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
    </div>
     <nav class="mb-4">
        <a href="{% url 'catalog:home' %}">Список товаров</a>
        <a href="{% url 'catalog:product_create' %}">Добавить товар</a>
    </nav>
</header>

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block title %}Skystore{% endblock %}

{% block content %}

{% include 'catalog/header.html' %}

<div class="row text-center">
    {% for product in products %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">
                    <a href="{% url 'catalog:product_detail' product.pk %}">{{ product.name }}</a>
                </h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ product.price }} руб.</h1>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- Описание: {{ product.description|truncatechars:100 }}</li>
                    <li>- Категория: {{ product.category }}</li>
                    <li>- Создано: {{ product.created_at|date:"d M Y" }}</li>
                    <li>- Обновлено: {{ product.updated_at|date:"d M Y" }}</li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
            </div>
        </div>
    </div>
{% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/menu.html
<nav>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/home/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        {% if user.is_authenticated %}
        <li class="p-2 btn btn-outline-primary">
            <form method="POST" action="{% url 'users:logout' %}" style="display: inline">
                {% csrf_token %}
                <button type="submit" class="btn btn-link nav-link">Выйти</button>
            </form>
        </li>

        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
    </div>
</nav>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block title %}Удалить продукт {{product.name}}{% endblock %}

{% block content %}
{% include 'catalog/header.html' %}

<h2>Удаление продукта</h2>
<p>Вы действительно хотите удалить {{ product.name }}?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'catalog:home' %}" class="btn btn-primary">Отменить</a>
</form>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block title %}Skystore{% endblock %}

{% block content %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ product.name }}</h1>
    <p class="lead">Подробная информация о товаре</p>
</div>

<div class="container mt-5">
    <p>Название товара - {{ product.name }}</p>
    <p>Описание товара - {{ product.description }}</p>
    <p>Фото товара - {{ product.image }}</p>
    <p>Категория товара - {{ product.category }}</p>
    <p>Дата создания - {{ product.created_at|date:"d M Y" }}</p>
    <p>Дата обновления - {{ product.updated_at|date:"d M Y" }}</p>

</div>
{% if request.user == product.owner or perms.catalog.change_product %}
<a href="{% url 'catalog:product_update' product.pk %}" class="btn btn-secondary">Редактировать</a>
{% endif %}
{% if request.user == product.owner or perms.catalog.delete_product %}
<a href="{% url 'catalog:product_delete' product.pk %}" class="btn btn-danger">Удалить</a>
{% endif %}
<a href="{% url 'catalog:home' %}" class="btn btn-primary">Вернуться к списку</a>

{% if perms.catalog.unpublish_product %}
    <form method="post" action="{% url 'catalog:product_is_published' product.id %}">
        {% csrf_token %}
        <button type="submit">Публиковать</button>
    </form>
{% endif %}

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block title %}Добавить продукт {{product.name}}{% endblock %}

{% block content %}
{% include 'catalog/header.html' %}

<h2>Форма для продукта</h2>
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'catalog:home' %}" class="btn btn-primary">Отменить</a>
</form>

{% endblock %}

catalog/templates/catalog/products_by_category.html
{% extends 'catalog/base.html' %}

{% block title %}Skystore{% endblock %}

{% block content %}

{% include 'catalog/header.html' %}

<h1>Товары в выбранной категории</h1>
<div class="row text-center">
    {% for product in products %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">
                    <a href="{% url 'catalog:product_detail' product.pk %}">{{ product.name }}</a>
                </h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ product.price }} руб.</h1>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- Описание: {{ product.description|truncatechars:100 }}</li>
                    <li>- Категория: {{ product.category }}</li>
                    <li>- Создано: {{ product.created_at|date:"d M Y" }}</li>
                    <li>- Обновлено: {{ product.updated_at|date:"d M Y" }}</li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
            </div>
        </div>
    </div>
{% endfor %}
</div>

{% endblock %}